language: python
python: 3.6
sudo: true

install:
  # install everything from apt.txt
  - sudo apt-get -y install $(grep -vE "^\s*#" apt.txt | tr "\n" " ")
  
  # install dependencies
  - pip install -r requirements.txt
  
script:
  # compile notebooks
  - mkdir ./nb
  - jupyter nbconvert --to html --output-dir='./nb' *.ipynb
  - jupyter nbconvert --to slides --output-dir='./nb' *.ipynb
  
  # download the latest classroom application
  - wget https://github.com/mmaelicke/notebook-classroom/releases/latest/download/notebook-classroom.zip
  - unzip ./notebook-classroom.zip -d ./dist
  
  # place the notebooks into the application
  - mv ./nb/* ./dist/nb
  
  - ls ./dist
  
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: ./dist
    on:
      branch: master
